/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./components/Background.vue')['default']
    DevSet: typeof import('./components/DevSet.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./components/Footer.vue')['default']
    Hitokoto: typeof import('./components/Hitokoto.vue')['default']
    Links: typeof import('./components/Links.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    MoreContent: typeof import('./components/MoreContent.vue')['default']
    Music: typeof import('./components/Music.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    Set: typeof import('./components/Set.vue')['default']
    SocialLinks: typeof import('./components/SocialLinks.vue')['default']
    TimeCapsule: typeof import('./components/TimeCapsule.vue')['default']
    Weather: typeof import('./components/Weather.vue')['default']
  }
}

// For TSX support
declare global {
  const Background: typeof import('./components/Background.vue')['default']
  const DevSet: typeof import('./components/DevSet.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElCollapse: typeof import('element-plus/es')['ElCollapse']
  const ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElProgress: typeof import('element-plus/es')['ElProgress']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElSlider: typeof import('element-plus/es')['ElSlider']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const Footer: typeof import('./components/Footer.vue')['default']
  const Hitokoto: typeof import('./components/Hitokoto.vue')['default']
  const Links: typeof import('./components/Links.vue')['default']
  const Loading: typeof import('./components/Loading.vue')['default']
  const Message: typeof import('./components/Message.vue')['default']
  const MoreContent: typeof import('./components/MoreContent.vue')['default']
  const Music: typeof import('./components/Music.vue')['default']
  const Player: typeof import('./components/Player.vue')['default']
  const ProgressBar: typeof import('./components/ProgressBar.vue')['default']
  const Set: typeof import('./components/Set.vue')['default']
  const SocialLinks: typeof import('./components/SocialLinks.vue')['default']
  const TimeCapsule: typeof import('./components/TimeCapsule.vue')['default']
  const Weather: typeof import('./components/Weather.vue')['default']
}